name: GitHub Wiki Action
author: Matthias Poortvliet <matthias.poortvliet@kpn.com>
description: 📖 Deploy docs from your source tree to the GitHub wiki
branding:
  icon: book
  color: blue
inputs:
  repository:
    description: >-
      The repository housing the wiki. Use this if you're publishing to a wiki
      that's not the current repository. You can change the GitHub server with
      the github-server-url input. Default is github.repository.
    required: true
    default: ${{ github.repository }}
  github-server-url:
    description: >-
      An alternate https://github.com URL, usually for GitHub Enterprise
      deployments under your own domain. Default is github.server_url (usually
      https://github.com).
    required: true
    default: ${{ github.server_url }}
  token:
    description: >-
      github.token is the default. This token is used when cloning and pushing
      wiki changes.
    required: true
    default: ${{ github.token }}
  path:
    description: >-
      The directory to use for your wiki contents. Default wiki.
    required: true
    default: wiki
  commit-message:
    description: >-
      The message to use when committing new content. Default is 'Update wiki
      github.sha'. You probably don't need to change this, since this only
      applies if you look really closely in your wiki.
    required: true
    default: Update wiki ${{ github.sha }}
  preprocess:
    description: >-
      If this option is true, we will preprocess the wiki to move the README.md
      to Home.md as well as rewriting all .md links to be bare links. This helps
      ensure that the Markdown works in source control as well as the wiki. The
      default is true.
    required: true
    default: true
outputs:
  wiki_url:
    description: >-
      The HTTP URL that points to the deployed repository's wiki tab. This is
      essentially the concatenation of github.server_url, github.repository, and
      the /wiki page.
    value: ${{ steps.main.outputs.wiki_url }}
runs:
  using: composite
  steps:
    - name: Ensure exec.sh is executable
      run: chmod +x .github/actions/push-to-wiki/exec.sh
      shell: bash
    - id: main
      run: '"${GITHUB_ACTION_PATH%/}/exec.sh"'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_SERVER_URL:  ${{ inputs.github-server-url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        WIKI: ${{ inputs.path }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}