#!/bin/sh
# Copyright 2023 Jacob Hummer
# SPDX-License-Identifier: Apache-2.0
# Based on https://github.com/jcbhmr/deno_wrapper
echo $GITHUB_ACTOR
WIKI_COMMIT_MESSAGE='Automatically publish wiki'
GIT_REPOSITORY_URL="https://${GITHUB_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.wiki.git"
WIKI_DIR="${WIKI}"
echo "Checking out wiki repository"
tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
(
    cd "$tmp_dir" || exit 1
    git init -b master
    git remote add origin "$GIT_REPOSITORY_URL"
    git fetch
    echo "Removing Files, ensuring deletion."
    rm -r -f ./*
) || exit 1

echo "Copying contents of $WIKI_DIR"
cp -R "$WIKI_DIR" "$tmp_dir"

echo "Committing and pushing changes"
(
    cd "$tmp_dir" || exit 1
    git add .
    git commit -m "$WIKI_COMMIT_MESSAGE"
    git push --set-upstream "$GIT_REPOSITORY_URL" master
) || exit 1

rm -rf "$tmp_dir"