services:
  scrollee:
    platform: linux/arm64
    image: heindetotverre/scrollee:latest
    restart: unless-stopped
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - VITE_S_PORT=3001
      - VITE_WS_PORT=3002
      - VITE_WS_HOST=0.0.0.0
      - VITE_WS_PATH=scrollee.heindetotverre.com
      - NODE_ENV=production
    ports:
      - "0.0.0.0:3001:3001"
      - "0.0.0.0:3002:3002"
    networks:
      - scrollee-net
    command: node dist/server/src/app.js

networks:
  scrollee-net:
    driver: bridge