services:
  scrollee:
    platform: linux/arm64
    image: ${IMAGE}
    restart: unless-stopped
    env_file:
      - shared/env/.env.production
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - NODE_ENV=production
    ports:
      - "3001:3001"
      - "3002:3002"
    networks:
      - scrollee-net
    command: node dist/server/src/app.js
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - scrollee-net

networks:
  scrollee-net:
    driver: bridge