name: Publish wiki
on:
  push:
    branches: 
      - 'feature/**'
    paths:
      - wiki/**
      - .github/workflows/publish-wiki.yml
      - .github/actions/push-to-wiki/action.yml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  models: read
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  security-events: write
  statuses: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: 🔎 Checkout
        uses: actions/checkout@v4
      - name: Push to Wiki
        uses: ./.github/actions/push-to-wiki
        with:
          token: ${{ secrets.PRIVATE_REPO_ACCESS_KEY }}