name: Publish wiki
on:
  push:
    branches: 
      - 'feature/**'
    paths:
      - wiki/**
      - .github/workflows/publish-wiki.yml
      - .github/actions/push-to-wiki/action.yml
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
    id-token: write
    contents: write
    issues: read
jobs:
  publish-wiki:
    runs-on: self-hosted\
    permissions:
      id-token: write
      contents: write
      issues: read
    steps:
      - name: 🔎 Checkout
        uses: actions/checkout@v4
      - name: Push to Wiki
        uses: ./.github/actions/push-to-wiki